channels:
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::cython
 - conda-forge::python=3.6.9
 - conda-forge::r-irkernel
 - conda-forge::cmake
 - conda-forge::r-base=3.5.1
 - conda-forge::r-essentials
 - conda-forge::gsl
 - conda-forge::tzlocal
 - conda-forge::simplegeneric
 - conda-forge::natsort
 - conda-forge::h5py
 - conda-forge::tqdm
 - conda-forge::patsy
 - conda-forge::llvmlite
 - conda-forge::numba
 - conda-forge::networkx
 - conda-forge::joblib
 - conda-forge::numexpr
 - conda-forge::pytables
 - conda-forge::statsmodels
 - conda-forge::python-igraph
 - conda-forge::louvain
 - conda-forge::r-rcpp
 - conda-forge::r-devtools
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-biocmanager
 - conda-forge::r-ape
 - conda-forge::r-askpass
 - conda-forge::r-assertthat
 - conda-forge::r-backports
 - conda-forge::r-base64enc
 - conda-forge::r-bh
 - conda-forge::r-bitops
 - conda-forge::r-blob
 - conda-forge::r-boot
 - conda-forge::r-brew
 - conda-forge::r-brio
 - conda-forge::r-broom
 - conda-forge::r-callr
 - conda-forge::r-caret
 - conda-forge::r-cellranger
 - conda-forge::r-class
 - conda-forge::r-cli
 - conda-forge::r-clipr
 - conda-forge::r-cluster
 - conda-forge::r-codetools
 - conda-forge::r-colorspace
 - conda-forge::r-commonmark
 - conda-forge::r-covr
 - conda-forge::r-cpp11
 - conda-forge::r-crayon
 - conda-forge::r-crosstalk
 - conda-forge::r-crul
 - conda-forge::r-curl
 - conda-forge::r-data.table
 - conda-forge::r-dbi
 - conda-forge::r-dbplyr
 - conda-forge::r-desc
 - conda-forge::r-diffobj
 - conda-forge::r-digest
 - conda-forge::r-dplyr
 - conda-forge::r-dqrng
 - conda-forge::r-dt
 - conda-forge::r-ellipsis
 - conda-forge::r-essentials
 - conda-forge::r-evaluate
 - conda-forge::r-fansi
 - conda-forge::r-farver
 - conda-forge::r-fastmap
 - conda-forge::r-forcats
 - conda-forge::r-foreach
 - conda-forge::r-foreign
 - conda-forge::r-formatr
 - conda-forge::r-fs
 - conda-forge::r-futile.logger
 - conda-forge::r-futile.options
 - conda-forge::r-generics
 - conda-forge::r-ggplot2
 - conda-forge::r-gh
 - conda-forge::r-gistr
 - conda-forge::r-git2r
 - conda-forge::r-glmnet
 - conda-forge::r-glue
 - conda-forge::r-gower
 - conda-forge::r-gtable
 - conda-forge::r-haven
 - conda-forge::r-hexbin
 - conda-forge::r-highr
 - conda-forge::r-hms
 - conda-forge::r-htmltools
 - conda-forge::r-htmlwidgets
 - conda-forge::r-httpcode
 - conda-forge::r-httpuv
 - conda-forge::r-httr
 - conda-forge::r-igraph
 - conda-forge::r-ini
 - conda-forge::r-ipred
 - conda-forge::r-irdisplay
 - conda-forge::r-irkernel
 - conda-forge::r-irlba
 - conda-forge::r-isoband
 - conda-forge::r-iterators
 - conda-forge::r-jsonlite
 - conda-forge::r-kernsmooth
 - conda-forge::r-knitr=1.30
 - conda-forge::r-labeling=0.4.2
 - conda-forge::r-lambda.r=1.2.4
 - conda-forge::r-later
 - conda-forge::r-lattice
 - conda-forge::r-lava
 - conda-forge::r-lazyeval
 - conda-forge::r-lifecycle
 - conda-forge::r-locfit
 - conda-forge::r-lubridate
 - conda-forge::r-magrittr
 - conda-forge::r-maps
 - conda-forge::r-markdown
 - conda-forge::r-mass
 - conda-forge::r-matrix
 - conda-forge::r-matrixstats
 - conda-forge::r-memoise
 - conda-forge::r-mgcv
 - conda-forge::r-mime
 - conda-forge::r-modelmetrics
 - conda-forge::r-modelr
 - conda-forge::r-munsell
 - conda-forge::r-nlme
 - conda-forge::r-nnet
 - conda-forge::r-numderiv
 - conda-forge::r-openssl
 - conda-forge::r-pbdzmq
 - conda-forge::r-pillar
 - conda-forge::r-pkgbuild
 - conda-forge::r-pkgconfig
 - conda-forge::r-pkgload
 - conda-forge::r-plyr
 - conda-forge::r-praise
 - conda-forge::r-prettyunits
 - conda-forge::r-princurve
 - conda-forge::r-proc
 - conda-forge::r-processx
 - conda-forge::r-prodlim
 - conda-forge::r-progress
 - conda-forge::r-promises
 - conda-forge::r-pryr
 - conda-forge::r-ps
 - conda-forge::r-purrr
 - conda-forge::r-quantmod
 - conda-forge::r-r6
 - conda-forge::r-randomforest
 - conda-forge::r-rbokeh
 - conda-forge::r-rcmdcheck
 - conda-forge::r-rcppannoy
 - conda-forge::r-rcpphnsw
 - conda-forge::r-rcurl
 - conda-forge::r-readr
 - conda-forge::r-readxl
 - conda-forge::r-recipes
 - conda-forge::r-recommended
 - conda-forge::r-rematch
 - conda-forge::r-rematch2
 - conda-forge::r-remotes
 - conda-forge::r-repr
 - conda-forge::r-reprex
 - conda-forge::r-reshape2
 - conda-forge::r-rex
 - conda-forge::r-rlang
 - conda-forge::r-rmarkdown
 - conda-forge::r-roxygen2
 - conda-forge::r-rpart
 - conda-forge::r-rprojroot
 - conda-forge::r-rstudioapi
 - conda-forge::r-rsvd
 - conda-forge::r-rversions
 - conda-forge::r-rvest
 - conda-forge::r-scales
 - conda-forge::r-selectr
 - conda-forge::r-sessioninfo
 - conda-forge::r-shape
 - conda-forge::r-shiny
 - conda-forge::r-sitmo
 - conda-forge::r-snow
 - conda-forge::r-sourcetools
 - conda-forge::r-spatial
 - conda-forge::r-squarem
 - conda-forge::r-statmod
 - conda-forge::r-stringi
 - conda-forge::r-stringr
 - conda-forge::r-survival
 - conda-forge::r-sys
 - conda-forge::r-testthat
 - conda-forge::r-tibble
 - conda-forge::r-tidyr
 - conda-forge::r-tidyselect
 - conda-forge::r-tidyverse
 - conda-forge::r-timedate
 - conda-forge::r-tinytex
 - conda-forge::r-triebeard
 - conda-forge::r-ttr
 - conda-forge::r-urltools
 - conda-forge::r-usethis
 - conda-forge::r-utf8
 - conda-forge::r-uuid
 - conda-forge::r-vctrs
 - conda-forge::r-viridislite
 - conda-forge::r-waldo
 - conda-forge::r-whisker
 - conda-forge::r-withr
 - conda-forge::r-xfun
 - conda-forge::r-xml2
 - conda-forge::r-xopen
 - conda-forge::r-xtable
 - conda-forge::r-xts
 - conda-forge::r-yaml
 - conda-forge::r-zeallot
 - conda-forge::r-zoo
 - conda-forge::r-rngtools
 - conda-forge::r-gam
 - bioconda::bioconductor-mast
 - bioconda::bioconductor-monocle
 - bioconda::bioconductor-complexheatmap
 - bioconda::bioconductor-clusterexperiment
 - bioconda::bioconductor-slingshot
 - bioconda::bioconductor-scran
 - bioconda::bioconductor-slingshot
 - bioconda::bioconductor-beachmat
 - bioconda::bioconductor-biobase
 - bioconda::bioconductor-biocgenerics
 - bioconda::bioconductor-biocneighbors
 - bioconda::bioconductor-biocparallel
 - bioconda::bioconductor-biocsingular
 - bioconda::bioconductor-bluster
 - bioconda::bioconductor-delayedarray
 - bioconda::bioconductor-delayedmatrixstats
 - bioconda::bioconductor-edger
 - bioconda::bioconductor-genomeinfodb
 - bioconda::bioconductor-genomeinfodbdata
 - bioconda::bioconductor-genomicranges
 - bioconda::bioconductor-hdf5array
 - bioconda::bioconductor-iranges
 - bioconda::bioconductor-limma
 - bioconda::bioconductor-matrixgenerics
 - bioconda::bioconductor-rhdf5
 - bioconda::bioconductor-rhdf5filters
 - bioconda::bioconductor-rhdf5lib
 - bioconda::bioconductor-s4vectors
 - bioconda::bioconductor-scuttle
 - bioconda::bioconductor-singlecellexperiment
 - bioconda::bioconductor-sparsematrixstats
 - bioconda::bioconductor-summarizedexperiment
 - bioconda::bioconductor-xvector
 - bioconda::bioconductor-zlibbioc
 - pip
 - pip:
   - pandas
   - numpy
   - rpy2
   - jupyter-server-proxy
   - scikit-learn
   - jupyter
   - jupyterlab
   - matplotlib
   - seaborn
   - MulticoreTSNE
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - scipy
   - leidenalg
   - plotly
   - cellbrowser
   - git+https://github.com/flying-sheep/anndata2ri
