channels:
 - conda-forge
 - bioconda
 - r
dependencies:
 - conda-forge::python=3.6.9
 - conda-forge::cython
 - conda-forge::r-irkernel
 - conda-forge::cmake
 - conda-forge::r-base=3.5.1
 - conda-forge::r-essentials
 - conda-forge::r-rgl
 - conda-forge::gsl
 - conda-forge::tzlocal
 - conda-forge::simplegeneric
 - conda-forge::natsort
 - conda-forge::h5py
 - conda-forge::tqdm
 - conda-forge::patsy
 - conda-forge::llvmlite
 - conda-forge::numba
 - conda-forge::networkx
 - conda-forge::joblib
 - conda-forge::numexpr
 - conda-forge::pytables
 - conda-forge::seaborn
 - conda-forge::statsmodels
 - conda-forge::python-igraph
 - conda-forge::louvain
 - conda-forge::r-rcpp
 - conda-forge::r-rngtools
 - r::r-stringi
 - conda-forge::r-devtools
 - conda-forge::r-gam
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-biocmanager
 - bioconda::bioconductor-rhdf5lib
 - bioconda::bioconductor-scran
 - bioconda::bioconductor-mast
 - bioconda::bioconductor-monocle
 - bioconda::bioconductor-complexheatmap
 - bioconda::bioconductor-clusterexperiment
 - bioconda::bioconductor-slingshot
 - pip
 - pip:
   - pandas
   - numpy
   - rpy2
   - jupyter-server-proxy
   - scikit-learn
   - jupyter
   - jupyterlab
   - matplotlib
   - seaborn
   - MulticoreTSNE
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - scipy
   - leidenalg
   - plotly
   - cellbrowser
   - git+https://github.com/flying-sheep/anndata2ri
