channels:
 - conda-forge
 - bioconda
 - r
dependencies:
 - conda-forge::cmake
 - conda-forge::r-essentials
 - conda-forge::r-rgl
 - conda-forge::scipy
 - conda-forge::gsl
 - conda-forge::tzlocal
 - conda-forge::simplegeneric
 - conda-forge::natsort
 - conda-forge::h5py
 - conda-forge::tqdm
 - conda-forge::patsy
 - conda-forge::llvmlite
 - conda-forge::numba
 - conda-forge::networkx
 - conda-forge::joblib
 - conda-forge::numexpr
 - conda-forge::pytables
 - conda-forge::statsmodels
 - conda-forge::python-igraph
 - conda-forge::louvain
 - conda-forge::r-rcpp
 - conda-forge::r-rngtools
 - r::r-stringi=1.4.3
 - conda-forge::r-devtools
 - conda-forge::r-gam
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-biocmanager
 - bioconda::bioconductor-rhdf5lib
 - bioconda::bioconductor-scran
 - bioconda::bioconductor-mast
 - bioconda::bioconductor-monocle
 - bioconda::bioconductor-complexheatmap
 - bioconda::bioconductor-clusterexperiment
 - bioconda::bioconductor-slingshot
 - pip
 - pip:
   - MulticoreTSNE
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - leidenalg
   - plotly
   - cellbrowser
   - git+https://github.com/flying-sheep/anndata2ri
