channels:
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::h5py
 - conda-forge::llvmlite
 - conda-forge::numba
 - conda-forge::networkx
 - conda-forge::joblib
 - conda-forge::python-igraph
 - conda-forge::louvain
 - conda-forge::umap-learn
 - conda-forge::cython
 - conda-forge::click
 - pip
 - pip:
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - scipy
   - scrublet
   - phate
   - PhenoGraph
   - leidenalg
   - plotly
   - iplotter
   - cellbrowser
   - scvelo
   - pybind11
   - hnswlib
   - velocyto
