channels:
 - conda-forge
 - bioconda
dependencies:
 - cmake
 - r-essentials
 - r-rgl
 - scipy
 - gsl
 - tzlocal
 - simplegeneric
 - natsort
 - h5py
 - tqdm
 - patsy
 - llvmlite
 - numba
 - networkx
 - joblib
 - numexpr
 - pytables
 - seaborn
 - statsmodels
 - python-igraph
 - louvain
 - r-rngtools
 - r-stringi
 - r-devtools
 - r-gam
 - r-rcolorbrewer
 - r-biocmanager
 - bioconductor-rhdf5lib
 - bioconductor-scran
 - bioconductor-mast
 - bioconductor-monocle
 - bioconductor-complexheatmap
 - bioconductor-slingshot
 - pip
 - pip:
   - MulticoreTSNE
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - rpy2
   - git+https://github.com/flying-sheep/anndata2ri
