channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.6.9
  - pandas=0.25.3
  - rpy2=3.1.0
  - r-base=3.5.1
  - bioconductor-biocinstaller=1.32.1
  - bioconductor-scran=1.10.1
  - #bioconductor-slingshot=1.4.0
  - scipy==1.1.0
  - statsmodels==0.9.0
  - numba=0.43.0
  - pytables
  - python-igraph==0.7.1.post6
  - louvain=0.6.1
  - cython
  - pip
  - pip:
    - scanpy==1.4.3
    - jupyter
    - jupyterlab
    - matplotlib
    - seaborn
    - sklearn
    - numpy
    - gprofiler-official==1.0.0
    - git+https://github.com/flying-sheep/anndata2ri.git
