channels:
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::python-igraph=0.10.1
 - pip
 - pip:
   - anndata==0.8.0
   - scanpy==1.9.1
   - scrublet==0.2.3
   - phate==1.0.8
   - PhenoGraph==1.5.7
   - leidenalg==0.9.0
   - plotly==5.10.0
   - iplotter==0.4.3
   - cellbrowser==1.2.1
   - scvelo==0.2.4
   - velocyto==0.17.17
   - umap-learn==0.5.3
   - ipykernel==6.16.5
   - nbconvert==7.2.1